using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            
            CharacterSetupButton.OnPressed += _ => 
            {
                SwitchState(LobbyGuiState.CharacterSetup);
            };
        }

        public void SwitchState(LobbyGuiState state)
        {
            if (DefaultState != null)
                DefaultState.Visible = (state == LobbyGuiState.Default);
                
            if (CharacterSetupState != null)
                CharacterSetupState.Visible = (state == LobbyGuiState.CharacterSetup);

            if (state == LobbyGuiState.CharacterSetup)
            {
                UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
            }
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup,
        }
    }
}